cols_dict = {
    "ust_left":"UST left deposited",
    "DEPOSIT_AMOUNT":"Amount deposited",
    "DEPOSIT_NET":"Deposited amount (UST)",
    "DEPOSIT_TXS":"N° of deposit txs",
    "DEP_USERS":"N° of depositing users",
    "HR":"Time",
    "NET_AMOUNT":"Net amount deposited",
    "TOT_TXS":"N° of txs",
    "TOT_USERS":"N° of users",
    "WITH_AMOUNT":"Withdrawn amount",
    "WITH_TXS":"N° of withdraw txs",
    "WITH_USERS":"N° of withdrawing users",
    'AMOUNT':'Amount deposited (UST)',
    'AVG_BALANCE_USD':'Average balance in the last 30 days (UST)',
    'N_TXS':'N° of txs',
    'SENDER':'User address',
    'N_USERS':'N° of users',
    'bucket_name':'Deposit range',
    'cumsum_ust':'Cumulative UST amount',
    'NEW_USERS': 'New Users',
    'cumsum_new_users': 'Cumulative new users',
    'TIME': 'Time',
    'MIN_DATE':'Date wallet creation',
    'ADDRESS_COUNT':'Number of wallets',
    'TYPE':'Protocol launch',
    'PARTICIPATE_TYPE':'User participation',
    'PARTICIPANTS':'Number of participants',
    'PERC_WITHDRAWN':'% withdrawn of the deposited amount',
    'net_ust': 'Amount UST',
    'perc_withdrawn_cat':'Percentage withdrawn UST bucket',
    'DEP_CAT':'Deposited UST range',
    'perc_withdrawn_cat_label':'Percentage UST withdrawn',
    'DEP_CAT_label':'UST deposited range',
    'sender':'User address',
    'deposited_p1':'Total deposited in Phase 1',
    'WITHDRAWN_AMOUNT_PHASE2':'Amount withdrawn in Withdrawal Only part of Phase 1',
    'perc_withdrawn_precise':'Percentage withdrawn out of total deposited'
}


